name: Build and publish
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up MSBuild and NuGet Path
      run:
        echo "Setting up MSBuild and NuGet paths..."
          echo "D:\vs2017\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\Common7\IDE\VC\VCPackages" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\Common7\IDE\CommonExtensions\Microsoft\TestWindow" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\MSBuild\15.0\bin\Roslyn" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\Team Tools\Performance Tools\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\Team Tools\Performance Tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\HTML Help Workshop" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\Windows Kits\10\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\\MSBuild\15.0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Windows\Microsoft.NET\Framework64\v4.0.30319" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\Common7\IDE\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\Common7\Tools\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\VulkanSDK\1.4.304.0\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\VMware\VMware Workstation\bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\Microsoft MPI\Bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\ImageMagick-7.1.1-Q16-HDRI" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Windows\system32" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Windows" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Windows\System32\Wbem" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Windows\System32\WindowsPowerShell\v1.0\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Windows\System32\OpenSSH\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\nodejs\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\dotnet\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\Windows Live\Shared" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\AppData\Local\Microsoft\WindowsApps" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\Git\cmd" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\PuTTY\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\CMake\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\NVIDIA Corporation\NVIDIA app\NvDLISR" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\msys64\ucrt64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\7-Zip" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\Certbot\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\onpath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\Meson\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\PowerShell\7\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\Docker\Docker\resources\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\php" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\ComposerSetup\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\Superluminal\Performance" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\PowerShell\7-preview\preview" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\MySQL\MySQL Shell 8.0\bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files (x86)\Common Files\Oracle\Java\javapath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\Downloads\7za920" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\AppData\Roaming\npm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\AppData\Local\GitHubDesktop\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\AppData\Local\Programs\Microsoft VS Code\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\Documents\emsdk\upstream\emscripten" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\AppData\Local\Programs\Ollama" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\AppData\Roaming\Composer\vendor\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "D:\vs2017\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Users\maksw\AppData\Local\AzureFunctionsTools\Releases\1.13.2\cli_x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Set up Enviorment & Restore NuGet packages
      run: |
        nuget restore code/SilkRAD.sln
    - name: Build Debug
      run: msbuild code/SilkRAD.sln /p:Configuration=Debug
    - name: Build Release
      run: msbuild code/SilkRAD.sln /p:Configuration=Release
    - name: Publish Artifact Debug
      uses: actions/upload-artifact@v4.3.3
      with:
        name: SilkRAD Debug
        path: |
          code\x64\Debug\*.dll
          code\x64\Debug\*.exe
          code\x64\Debug\*.pdb
        if-no-files-found: 'error'
        compression-level: 0
    - name: Publish Artifact Release
      uses: actions/upload-artifact@v4.3.3
      with:
        name: SilkRAD Release
        path: |
          code\x64\Release\*.dll
          code\x64\Release\*.exe
          code\x64\Release\*.pdb
        if-no-files-found: 'error'
        compression-level: 0
