name: Build and publish
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CUDA toolkit
      uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        cuda: '10.0.130'
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '15.7'
    - name: Set up Windows SDK
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
      id: windows-sdk
      with:
        sdk-version: '17763'
    - name: Copy BuildCustomizations
      shell: bash
      run: |
        cp -R "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\extras\\visual_studio_integration\\MSBuildExtensions\\." "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\BuildCustomizations"
        cp -R "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\extras\\visual_studio_integration\\MSBuildExtensions\\." "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v160\BuildCustomizations"
        cp -R "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\extras\\visual_studio_integration\\MSBuildExtensions\\." "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v150\BuildCustomizations"
    - name: Restore NuGet packages
      run: nuget restore code/SilkRAD.sln
    - name: Build Release
      run: msbuild code/SilkRAD.sln /p:Configuration=Release
	  - name: Build Debug
	    run: msbuild code/SilkRAD.sln /p:Configuration=Debug
    - name: Publish Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: SilkRAD Release
        path: code\x64\Release
        if-no-files-found: 'error'
		compression-level: 0
		name: SilkRAD Debug
		path: code\x64\Debug
		if-no-files-found: 'error'
		compression-level: 0
